import Head from 'next/head'
import style from '../styles/layout.module.css'
import Menu from './menu'
import ShLike from './shLike'


export default function Layout( {children,title} ){
    return (
        <>
            <div>
                <Head>
                    <title>CM {title? ` | ${title}`:""}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link rel ="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css'/>
                </Head>
            </div>
            <Menu/>
            <div className={style.container}>{children}</div>
            <ShLike/>
        </>
    )
}